# Generated by Django 4.0.1 on 2022-01-31 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Dep_id',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LeaveType', models.CharField(max_length=50)),
                ('Reason', models.CharField(max_length=100)),
                ('Startdate', models.DateField(null=True)),
                ('Enddate', models.DateField(null=True)),
                ('employe_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employeeapi.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_name', models.CharField(max_length=100)),
                ('Branch', models.CharField(max_length=100)),
                ('Department_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employeeapi.employee')),
            ],
        ),
    ]
