# Generated by Django 4.0.1 on 2022-01-31 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0002_employee_dep_id_leaves_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(null=True)),
                ('project_name', models.CharField(max_length=100)),
                ('Startdate', models.DateField(null=True)),
                ('Enddate', models.DateField(null=True)),
                ('project_status', models.CharField(max_length=20)),
                ('Employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employeeapi.employee')),
            ],
        ),
    ]
